spring.application.name=app
logging.file.name=/var/log/backend/app.log
logging.file.max-size=10MB
logging.file.max-history=7
spring.mongodb.uri=mongodb://admin:secret@localhost:27017/Blue-App?authSource=admin
# Must be a base64-encoded string that decodes to at least 32 bytes (256 bits for HS256)
jwt.secret=c0tnHPk+muexuG/BOojSW7oyXxms72b0oyWw2LT6LSs=
# 15 minutes
jwt.access-token-expiry=900000
# 7 days
jwt.refresh-token-expiry=604800000
